language: generic

env:
  global:
    - CONDACI_PYPI_SDIST_UPLOAD_PY_VER=3.9
    - BINSTAR_USER=menpo

jobs:
  include:
    - os: osx
      osx_image: xcode9.4
      env: PYTHON_VERSION=3.6
    - os: osx
      osx_image: xcode9.4
      env: PYTHON_VERSION=3.9
    - os: linux
      dist: bionic
      env: PYTHON_VERSION=3.6
    - os: linux
      dist: bionic
      env: PYTHON_VERSION=3.7
    - os: linux
      dist: bionic
      env: PYTHON_VERSION=3.8
    - os: linux
      dist: bionic
      env: PYTHON_VERSION=3.9

install:
- wget https://raw.githubusercontent.com/menpo/condaci/v0.5.x/condaci.py -O condaci.py
- python condaci.py setup --channels conda-forge

script:
- ~/miniconda/bin/python condaci.py build ./conda

notifications:
  email: false
